export const USER_NUMBER_REQUEST = 'USER_NUMBER_REQUEST';
export const USER_NUMBER_SUCCESS = 'USER_NUMBER_SUCCESS';
export const USER_NUMBER_FAIL = 'USER_NUMBER_FAIL';

export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_VERIFY_FAIL = 'USER_VERIFY_FAIL';

export const USER_RESEND_REQUEST = 'USER_RESEND_REQUEST';
export const USER_RESEND_SUCCESS = 'USER_RESEND_SUCCESS';
export const USER_RESEND_FAIL = 'USER_RESEND_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
